/**
 * PDF Report Generator using PDFKit
 */

import PDFDocument from 'pdfkit'
import { logger } from '../logger'

export interface PDFReportOptions {
  title: string
  subtitle?: string
  dateRange?: string
  data: any[]
  columns: string[]
  summary?: Record<string, any>
}

/**
 * Generate PDF report
 */
export async function generatePDF(options: PDFReportOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: {
          top: 50,
          bottom: 50,
          left: 50,
          right: 50,
        },
      })

      const chunks: Buffer[] = []

      doc.on('data', (chunk) => chunks.push(chunk))
      doc.on('end', () => resolve(Buffer.concat(chunks)))
      doc.on('error', reject)

      // Header
      doc
        .fontSize(24)
        .fillColor('#4F46E5')
        .text(options.title, { align: 'center' })
        .moveDown(0.5)

      if (options.subtitle) {
        doc
          .fontSize(14)
          .fillColor('#6B7280')
          .text(options.subtitle, { align: 'center' })
          .moveDown(0.5)
      }

      if (options.dateRange) {
        doc
          .fontSize(10)
          .fillColor('#9CA3AF')
          .text(options.dateRange, { align: 'center' })
          .moveDown(1)
      }

      // Line separator
      doc
        .strokeColor('#E5E7EB')
        .lineWidth(1)
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke()
        .moveDown(1)

      // Summary section
      if (options.summary) {
        doc
          .fontSize(16)
          .fillColor('#111827')
          .text('Summary', { underline: true })
          .moveDown(0.5)

        Object.entries(options.summary).forEach(([key, value]) => {
          doc
            .fontSize(12)
            .fillColor('#374151')
            .text(`${key}: `, { continued: true })
            .fillColor('#6B7280')
            .text(String(value))
        })

        doc.moveDown(1)
      }

      // Data table
      if (options.data && options.data.length > 0) {
        doc
          .fontSize(16)
          .fillColor('#111827')
          .text('Campaign Performance', { underline: true })
          .moveDown(0.5)

        // Table headers
        const startY = doc.y
        const columnWidth = (545 - 50) / options.columns.length
        
        doc.fontSize(10).fillColor('#111827')
        
        options.columns.forEach((col, i) => {
          doc.text(col, 50 + i * columnWidth, startY, {
            width: columnWidth,
            align: 'left',
          })
        })

        doc.moveDown(0.3)

        // Table rows (limit to first 30 for PDF)
        const rowsToShow = options.data.slice(0, 30)
        
        rowsToShow.forEach((row, rowIndex) => {
          const rowY = doc.y
          
          // Alternate row colors
          if (rowIndex % 2 === 0) {
            doc
              .rect(50, rowY - 3, 495, 15)
              .fillColor('#F9FAFB')
              .fill()
          }

          doc.fillColor('#374151').fontSize(9)

          options.columns.forEach((col, i) => {
            const value = row[col.toLowerCase().replace(' ', '_')] || row[col] || ''
            doc.text(String(value), 50 + i * columnWidth, rowY, {
              width: columnWidth,
              align: 'left',
            })
          })

          doc.moveDown(0.5)

          // Check if need new page
          if (doc.y > 700) {
            doc.addPage()
          }
        })

        if (options.data.length > 30) {
          doc
            .moveDown(0.5)
            .fontSize(10)
            .fillColor('#9CA3AF')
            .text(`Showing 30 of ${options.data.length} total records. Download full data as CSV or Excel.`, {
              align: 'center',
            })
        }
      }

      // Footer
      const pages = doc.bufferedPageRange()
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i)
        
        doc
          .fontSize(8)
          .fillColor('#9CA3AF')
          .text(
            `Generated by AdPilot AI on ${new Date().toLocaleDateString()}`,
            50,
            doc.page.height - 50,
            { align: 'center' }
          )
          .text(
            `Page ${i + 1} of ${pages.count}`,
            50,
            doc.page.height - 35,
            { align: 'center' }
          )
      }

      doc.end()
    } catch (error) {
      logger.error('PDF generation failed', error)
      reject(error)
    }
  })
}

/**
 * Format campaign data for PDF export
 */
export function formatCampaignDataForPDF(
  campaigns: any[],
  dateRange?: { start: string; end: string }
): PDFReportOptions {
  const totalSpend = campaigns.reduce((sum, c) => sum + parseFloat(c.spend || 0), 0)
  const totalRevenue = campaigns.reduce((sum, c) => sum + parseFloat(c.revenue || c.purchase_value || 0), 0)
  const totalConversions = campaigns.reduce((sum, c) => sum + parseInt(c.conversions || 0), 0)
  const avgROAS = totalSpend > 0 ? totalRevenue / totalSpend : 0

  return {
    title: 'Campaign Performance Report',
    subtitle: 'AI Facebook Ads Command Center',
    dateRange: dateRange
      ? `Period: ${dateRange.start} to ${dateRange.end}`
      : `Generated: ${new Date().toLocaleDateString()}`,
    columns: ['Campaign', 'Spend', 'Revenue', 'ROAS', 'Conversions'],
    data: campaigns.map(c => ({
      campaign: c.name || c.campaign_name,
      spend: `$${parseFloat(c.spend || 0).toFixed(2)}`,
      revenue: `$${parseFloat(c.revenue || c.purchase_value || 0).toFixed(2)}`,
      roas: parseFloat(c.roas || 0).toFixed(2) + 'x',
      conversions: parseInt(c.conversions || 0),
    })),
    summary: {
      'Total Campaigns': campaigns.length,
      'Total Spend': `$${totalSpend.toFixed(2)}`,
      'Total Revenue': `$${totalRevenue.toFixed(2)}`,
      'Average ROAS': `${avgROAS.toFixed(2)}x`,
      'Total Conversions': totalConversions,
    },
  }
}

export default generatePDF
